"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
import sys
from setuptools import setup

INFO_PLIST_TEMPLATE = '''\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>%(name)s</string>
</dict>
</plist>
'''

try:
    with open(os.path.join(os.path.dirname(sys.executable), 'Info.plist'), 'w') as f:
        f.write(INFO_PLIST_TEMPLATE % {'name': 'gapa'})
except IOError:
    pass

APP = ['gapa.py']

DATA_FILES = [ ('images', ['images/circle.png']) ]

OPTIONS = {
    'argv_emulation': True,
    'iconfile':'images/icon.icns',
    'plist': {
        'LSUIElement': True,
    }
}

with open('README.adoc') as f:
    readme = f.read()

setup(
    name="Gapa",
    version="1.0.0",
    description="a mini tool that enables to hide desktop items",
    author="Hakan Ozler",
    url="https://github.com/ozlerhakan/gapa",
    license="MIT License",
    long_description=readme,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
